### ISSUE TITLE
SKR mini E3 V3.0 Third Thermistor Sensor

### ISSUE THREAD

**Issue by markxyx** [bigtreetech/BIGTREETECH-SKR-mini-E3#632]
Hi, is there any pin that I can use it as third thermistor sensor for heated chamber?
I tried Z stop and PS-on. No luck.

**Comment by markxyx** [comment]
> 

So damn hard...seem like using pi's pin would be much easier.

**Comment by radek8** [comment]
Measuring temperature is not the same as connecting a limit switch.
Temperature measurement is performed by measuring the voltage on a resistive divider that contains a thermistor.
You also can't connect a fan to a random pin. The fan must switch Mosfet.

**Comment by radek8** [comment]
Caution the processor has 3.3V logic and some pins are sensitive to higher voltages and can be destroyed by 5V voltages!

**Comment by Jaybeam** [comment]
I don't know iff you stil need this but I use pin PA5 for my chamber thermistor:

- On a E3 V2 this is the pin labeled SCK on the SPI1 header.
- On a E3 V2 this is the pin labeled CLK on the SPI1 header.

**Comment by ironhalik** [comment]
Oh man @Jaybeam - coming back back with an answer half a year later is going above and beyond. Thank you.
I'm going to try it.

**Comment by Dataro81** [comment]
![Screen Shot 2023-01-12 at 8 39 00 AM](https://user-images.githubusercontent.com/15877899/212111787-f84c4c30-b64d-42f6-907e-b85e793522ba.png)
Is this where the definition is? The diagram is confusing.

**Comment by Dataro81** [comment]
nm, just found out that sck and clk are different acronyms for the same thing. 
SCK stands for **S**pi **C**loc**K**. 
CLK stands for spi **CL**oc**K**.

**Comment by Dataro81** [comment]
> I don't know if you stil need this but I use pin PA5 for my chamber thermistor:
> 
> * On a E3 V2 this is the pin labeled SCK on the SPI1 header.
> * On a E3 V2 this is the pin labeled CLK on the SPI1 header.

For the second line, i think you meant to write E3 V3, right?

**Comment by NonaSuomy** [comment]
For the E3 V3.0 you can connect a 3rd thermistor to MOSI on the ISP 8 Pin Header I tested this with the Umbilical board for a Voron 0.1 it does cause issues with the SD Card but it's not too much of problem with Klipper you can just disable it then update firmware etc.
![image](https://user-images.githubusercontent.com/1906575/212625498-1c536966-deea-4095-a7a2-9949bd1d1372.png)

For Klipper
```yaml
#####################################################################
#   Chamber Temperature Sensor
#####################################################################

[temperature_sensor Chamber_Temp]
sensor_type: Generic 3950
sensor_pin: PA7 # PA7 is MOSI on the SPI header. Has an onboard 10K pullup to 3v3. Connect the other leg of the thermistor to ground
pullup_resistor: 10000
```

![image](https://user-images.githubusercontent.com/1906575/212625440-7e3d51f8-0e02-44fd-a1fd-b310eaa2a818.png)
